name: Run test.py and save Excel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-test-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run test.py
      run: python test.py

    - name: Upload Excel file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: scraped-excel-output
        path: |
          *.xlsx  # <-- adjust this if your Excel file has a specific name or path
